In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("ecommerce_sales_analytics_5000.csv")

In [ ]:
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

In [ ]:
df.shape

(5000, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   object
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), object(4)
memory usage: 468.9+ KB

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
region              0
quantity            0
unit_price          0
discount            0
payment_method      0
delivery_days       0
customer_rating     0
revenue             0
dtype: int64

In [ ]:
df.describe()

,order_id,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
std,1443.520003,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219
min,10001.000000,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000

In [ ]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue'],
      dtype='object')

In [ ]:
df['order_date'].head()

0    1/1/2022
1    1/2/2022
2    1/3/2022
3    1/4/2022
4    1/5/2022
Name: order_date, dtype: object

In [20]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [21]:
df['order_date'].dtype

dtype('<M8[ns]')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[ns]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(4), object(3)
memory usage: 468.9+ KB

In [24]:
df[['quantity','unit_price','discount','revenue']].head(10)

   quantity  unit_price  discount  revenue
0         7      373.65      0.28  1883.20
1         7       47.74      0.09   304.10
2         3      311.28      0.31   644.35
3         5      524.47      0.02  2569.90
4         5      139.87      0.33   468.56
5         2      264.44      0.20   423.10
6         6      564.60      0.23  2608.45
7         6      265.71      0.13  1387.01
8         6      224.65      0.27   983.97
9         4      272.71      0.06  1025.39

In [25]:
expected_revenue = (df['quantity'] * df['unit_price'] * (1 - df['discount'])).round(2)
(df['revenue']-expected_revenue).abs().round(2).describe()

count    5000.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
dtype: float64

In [26]:
df['order_year'] = df['order_date'].dt.year

In [27]:
df[['order_date', 'order_year']].head()

  order_date  order_year
0 2022-01-01        2022
1 2022-01-02        2022
2 2022-01-03        2022
3 2022-01-04        2022
4 2022-01-05        2022

In [28]:
df['order_month'] = df['order_date'].dt.month

In [29]:
df[['order_date', 'order_year', 'order_month']].head(10)

  order_date  order_year  order_month
0 2022-01-01        2022            1
1 2022-01-02        2022            1
2 2022-01-03        2022            1
3 2022-01-04        2022            1
4 2022-01-05        2022            1
5 2022-01-06        2022            1
6 2022-01-07        2022            1
7 2022-01-08        2022            1
8 2022-01-09        2022            1
9 2022-01-10        2022            1

In [31]:
df.shape

(5000, 14)

In [32]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue', 'order_year', 'order_month'],
      dtype='object')

In [35]:
df.to_csv('ecommerce_sales_transformed.csv', index=False)

In [34]:
import os
os.path.exists('ecommerce_sales_transformed.csv')

True

In [36]:
from google.colab import files

files.download('ecommerce_sales_transformed.csv')